[pytest]
log_cli=true
# activate DEBUG log level, if needed
log_level=DEBUG

# --ignore-glob -> ignore given path patterns with glob
# --ignore-glob -> only working in the console, not when invoking pytest.main
#addopts = --ignore-glob=submodules/xx/*
