# SPDX-FileCopyrightText: 2024 Deutsche Telekom AG
#
# SPDX-License-Identifier: CC0-1.0    

# See https://reuse.software/spec-3.2/#reusetoml for specification
version = 1

# No special copyrights, e.g. screenshots or config files:
[[annotations]]
path = ["**/.gitignore", "pytest.ini", "metadata.txt", "modules/examples/qgis_default_icons.txt", ".gitmodules"]
precedence = "aggregate"
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "GPL-3.0-only"

# All ui files from the modules/examples:
[[annotations]]
path = ["modules/examples/*.ui"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Deutsche Telekom Technik GmbH <f.vonstudsinske@telekom.de>"
SPDX-License-Identifier = "GPL-3.0-only"

# template icons
[[annotations]]
path = ["templates/icons/icon.svg"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Deutsche Telekom Technik GmbH <f.vonstudsinske@telekom.de>"
SPDX-License-Identifier = "GPL-3.0-only"
