#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2026 Deutsche Telekom IT GmbH <leonard.buhl@telekom.de>
# SPDX-License-Identifier: GPL-3.0-only

set -euo pipefail

usage() {
    cat <<'EOF'
Usage: bash scripts/setup-qgis-dev.sh [QGIS installation directory]

Examples:
    bash scripts/setup-qgis-dev.sh
    bash scripts/setup-qgis-dev.sh 'C:\Program Files\QGIS 3.40.7'

The argument takes precedence over QGIS_ROOT. If neither is set, the newest
installation under C:\Program Files\QGIS* is selected.
EOF
}

if [[ $# -gt 1 ]]; then
    usage >&2
    exit 2
fi

case "${1:-}" in
    -h|--help)
        usage
        exit 0
        ;;
    -*)
        printf 'Unknown option: %s\n\n' "$1" >&2
        usage >&2
        exit 2
        ;;
esac

case "$(uname -s)" in
    CYGWIN*|MINGW*|MSYS*)
        ;;
    *)
        printf '%s\n' 'This setup script only supports Windows.' >&2
        exit 1
        ;;
esac

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
workspace_dir="$(cd "$script_dir/.." && pwd)"
requested_root="${1:-${QGIS_ROOT:-}}"

if [[ -f "$workspace_dir/.gitmodules" ]] && git -C "$workspace_dir" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    printf 'Initializing Git submodules ...\n'
    git -C "$workspace_dir" submodule sync --recursive
    git -C "$workspace_dir" submodule update --init --recursive
fi

if [[ -n "$requested_root" ]]; then
    if command -v cygpath >/dev/null 2>&1; then
        requested_root="$(cygpath -u "$requested_root")"
    fi
    qgis_root="$(cd "$requested_root" 2>/dev/null && pwd)" || {
        printf 'QGIS installation does not exist: %s\n' "$requested_root" >&2
        exit 1
    }
else
    candidates=()
    for candidate in /c/Program\ Files/QGIS*; do
        [[ -d "$candidate/apps" ]] && candidates+=("$candidate")
    done

    if [[ ${#candidates[@]} -eq 0 ]]; then
        printf '%s\n' 'No QGIS installation found under C:\Program Files.' >&2
        printf '%s\n' 'Pass its directory as the first argument or set QGIS_ROOT.' >&2
        exit 1
    fi

    qgis_root="$(printf '%s\n' "${candidates[@]}" | sort -V | tail -n 1)"
fi

python_candidates=()
for candidate in "$qgis_root"/apps/Python3*; do
    [[ -x "$candidate/python.exe" ]] && python_candidates+=("$candidate")
done
if [[ ${#python_candidates[@]} -eq 0 ]]; then
    printf 'Could not find apps\\Python3*\\python.exe below %s\n' "$qgis_root" >&2
    exit 1
fi
python_dir="$(printf '%s\n' "${python_candidates[@]}" | sort -V | tail -n 1)"

if [[ -d "$qgis_root/apps/qgis-ltr/python/qgis" ]]; then
    qgis_app_dir="$qgis_root/apps/qgis-ltr"
elif [[ -d "$qgis_root/apps/qgis/python/qgis" ]]; then
    qgis_app_dir="$qgis_root/apps/qgis"
else
    printf 'Could not find the QGIS Python package below %s\\apps.\n' "$qgis_root" >&2
    exit 1
fi

if command -v cygpath >/dev/null 2>&1; then
    qgis_root_windows="$(cygpath -w "$qgis_root")"
    qgis_python_windows="$(cygpath -w "$qgis_app_dir/python")"
else
    qgis_root_windows="$qgis_root"
    qgis_python_windows="$qgis_app_dir/python"
fi

venv_dir="$workspace_dir/.venv"
venv_python="$venv_dir/Scripts/python.exe"
marker_file="$venv_dir/.qgis-dev-root"
recreate=true

if [[ -x "$venv_python" && -f "$marker_file" ]]; then
    configured_root="$(tr -d '\r\n' < "$marker_file")"
    if [[ "${configured_root,,}" == "${qgis_root_windows,,}" ]]; then
        recreate=false
    fi
fi

if $recreate; then
    if [[ -e "$venv_dir" ]]; then
        printf 'Replacing the existing .venv because it was not created for %s.\n' "$qgis_root_windows"
        rm -rf "$venv_dir"
    fi
    printf 'Creating .venv with %s ...\n' "$python_dir/python.exe"
    env -u PYTHONHOME "$python_dir/python.exe" -m venv --system-site-packages "$venv_dir"
fi

site_packages="$venv_dir/Lib/site-packages"
printf '%s\n' "$qgis_python_windows" > "$site_packages/qgis-dev.pth"
printf '%s\n' "$qgis_root_windows" > "$marker_file"

# QGIS installations do not consistently include development tools. Ignore the
# user's site-packages here so every checkout gets its own pinned pytest and
# type stubs instead of accidentally relying on packages installed for one user.
printf 'Installing development dependencies ...\n'
env -u PYTHONHOME PYTHONNOUSERSITE=1 "$venv_python" -m pip install \
    --disable-pip-version-check \
    --requirement "$workspace_dir/requirements-dev.txt"

qgis_env_name="$(basename "$qgis_app_dir")"
cat > "$workspace_dir/.env" <<EOF
# Generated by scripts/setup-qgis-dev.sh; machine-local and intentionally ignored.
QGIS_ROOT=$qgis_root_windows
QGIS_ENVNAME=$qgis_env_name
PYTHONNOUSERSITE=1
EOF

printf 'Checking the environment ...\n'
env -u PYTHONHOME PYTHONNOUSERSITE=1 "$venv_python" -c 'import sys, pytest; from qgis.core import Qgis; print(f"Python {sys.version.split()[0]}, QGIS {Qgis.version()}, pytest {pytest.__version__}")'

cat <<'EOF'

QGIS development environment is ready.
Reload the VS Code window. The workspace selects .venv automatically.
Do not start VS Code through python-qgis*.bat and do not set PYTHONHOME.
EOF